name: "Deploy - API - POI (.NET Core)"

# run on push to main branch
on:
  push:
    branches:
      - main
    paths:
      - "apis/poi/**"
  workflow_dispatch:

# Set envs
env:
  WORKDIR: "apis/poi/web"
  DOCKER_IMAGE_BASE_NAME: "devopsoh/api-poi"
  API_NAME: "poi"
  # RESOURCES_PREFIX: "" # hardcoded or dynamic based on repo name

# Set defaults for GitHub Actions runner
defaults:
  run:
    working-directory: "apis/poi/web"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    outputs:
      RESOURCES_PREFIX: ${{ steps.resources_prefix.outputs.result }}
      DOCKER_IMAGE_FULL_NAME: ${{ steps.dockerfullname.outputs.DOCKER_IMAGE_FULL_NAME }}
    steps:
      - uses: actions/checkout@v2

      # Get RESOURCES_PREFIX based on the repo name
      - name: Get repo name
        uses: actions/github-script@v5
        id: resources_prefix
        with:
          result-encoding: string
          script: return context.repo.repo.toLowerCase()

      # AZURE CONTAINER REGISTRY
      - name: Get docker image full name
        run: |
          DOCKER_IMAGE_FULL_NAME=${{ steps.resources_prefix.outputs.result }}cr.azurecr.io/${{ env.DOCKER_IMAGE_BASE_NAME }}

          # Set for current Job
          echo "DOCKER_IMAGE_FULL_NAME=${DOCKER_IMAGE_FULL_NAME}" >> ${GITHUB_ENV}

          # Set for next Job
          echo "::set-output name=DOCKER_IMAGE_FULL_NAME::${DOCKER_IMAGE_FULL_NAME}"
        id: dockerfullname

      - name: "Azure Login"
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push Docker image using Azure Container Registry"
        uses: Azure/cli@v1
        with:
          inlineScript: az acr build --image ${{ env.DOCKER_IMAGE_BASE_NAME }}:${{ github.run_id }} --registry ${{ steps.resources_prefix.outputs.result }}cr.azurecr.io --build-arg build_version=${{ github.run_id }} --file ${{ env.WORKDIR }}/Dockerfile ${{ env.WORKDIR }}

  production:
    name: "Production"
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: POI Production
      url: "${{ steps.deploy-to-webapp.outputs.webapp-url }}/api/version/${{ env.API_NAME }}"
    env:
      RESOURCES_PREFIX: ${{ needs.build.outputs.RESOURCES_PREFIX }}
      DOCKER_IMAGE_FULL_NAME: "${{ needs.build.outputs.DOCKER_IMAGE_FULL_NAME }}"
    steps:
      # Login to Azure with Service Principal
      - name: "Azure Login"
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Set new Docker image in WebApp
      - name: Azure WebApp
        id: deploy-to-webapp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.RESOURCES_PREFIX }}${{ env.API_NAME }}
          images: "${{ env.DOCKER_IMAGE_FULL_NAME }}:${{ github.run_id }}"
